### ISSUE TITLE
AssertionError [ ] -- No transactions found <--- is this a bug ?

### ISSUE THREAD

**Issue by ivrusuboca** [pcko1/bscscan-python#9]
Hi. I am having , for another BSC address, thrown the following exception :

......./lib/python3.9/site-packages/bscscan/bscscan.py", line 33, in wrapper
    return parser.parse(r)
......./lib/python3.9/site-packages/bscscan/utils/parsing.py", line 12, in parse
    assert status, f"{result} -- {message}"
AssertionError: [] -- No transactions found

Is it expected to throw an error , opposite just returning nothing ? 

Thank you. Ionut.

**Comment by pcko1** [comment]
I get what you mean. 

I am afraid that this is a problem on BSCScan's side though, because they treat an empty list of transactions as an erroneous case, returning status code 0. From my side, if JSON response includes a status code of 0, I blindly handle it as an error and throw an exception. This is because a status code 0 may imply that **either** there are faulty parameter values **or** the address has no transactions.

For example:

- [Request 1](https://api.bscscan.com/api?module=account&action=txlist&address=0x0000000000000000000000000000000000001004&startblock=1&endblock=99999999&sort=asc&apikey=YourApiKeyToken) originally returns status code 1
- [Request 2](https://api.bscscan.com/api?module=account&action=txlist&address=0x0000000010000000000000000000000000001004&startblock=1&endblock=99999999&sort=asc&apikey=YourApiKeyToken) originally returns status code 0, thus it is handled as an error by this package

**Comment by hsyngmtrk** [comment]
Hello, I have been experiencing the same problem over and over again. I tried to tome up with different try-excepts, unfortunately none of them worked. Is it possible that you can write a try except code to avoid this assertion error? Thank you.

**Comment by k4vld** [comment]
> Hello, I have been experiencing the same problem over and over again. I tried to tome up with different try-excepts, unfortunately none of them worked. Is it possible that you can write a try except code to avoid this assertion error? Thank you.

async def getTransferHistory(address, firstBlock, lastBlock):
    try:
        async with BscScan(YOUR_API_KEY) as bsc:
            return await bsc.get_bep20_token_transfer_events_by_address(address, firstBlock, lastBlock, 'asc')
    except Exception as E:
        if str(E) == '[] -- No transactions found':
            return []
        else:
            print(f'Cannot request history from {firstBlock} to {lastBlock} due to {E}')
